version: 0.2

env:
    variables:
        PROJECT_NAME: sqs-kafka-forwarder
        DOCKER_BUILD: yes
        BUILD_TYPE: default
        S3_DEPLOY_CONFIG_DIR: applications/sqs-kafka-forwarder/
        BUCKET_NAME: factory-ci-cd
        S3_CICD_FUNCTIONS_DESTINATION: applications/cicd

phases: 
    install:
        runtime-versions:
            java: corretto17
        commands:
            - apt update -y
            - apt install docker.io curl -y
            - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
            - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
            - sudo apt install python3 -y
            - sudo apt install python3-pip -y
            - pip3 install kubernetes
            - pip3 install boto3
    pre_build:
        commands:
            - echo "Fetching repository token ..."
            - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain factory --domain-owner 781648067507 --region eu-central-1 --query authorizationToken --output text`
            - echo "Pulling settings.xml"
            - aws s3 cp s3://factory-ci-cd/settings.xml settings.xml
            - aws s3 cp s3://${BUCKET_NAME}/${S3_CICD_FUNCTIONS_DESTINATION}/ ./ --recursive
    build:
        commands:
            - echo "Building ..."
            - mvn -s settings.xml clean package -P ${BUILD_TYPE}
    post_build:
        commands:
            - echo "Publishing to artifact repository ..."
            - mvn -s settings.xml deploy
            - if [ "$DOCKER_BUILD" == "yes"]; then
            - echo "Building docker image ..."
            - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
            - docker build -t ${DOCKER_USERNAME}/${PROJECT_NAME} --build-arg DIRECTORY=target --build-arg SERVICE_NAME=$PROJECT_NAME .
            - docker push ${DOCKER_USERNAME}/${PROJECT_NAME}
            - ;fi
            - echo "Sending application manifests to S3 ..."
            - aws s3 cp kube s3://factory-ci-cd/applications/$PROJECT_NAME/ --recursive
            - python3 functions/deploy_notifier.py
cache:
    paths:
        - '/root/.m2/**/*'
        - '/root/.npm/**/*'
        - '/root/.pip-cache/**/*'
        - '/root/.docker/**'