apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-kafka-forwarder-deployment
  namespace: factory
  labels:
    app: sqs-kafka-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqs-kafka-forwarder
  template:
    metadata:
      labels:
        app: sqs-kafka-forwarder
    spec:
      containers:
        - name: sqs-kafka-forwarder
          imagePullPolicy: Always
          image: juliantheking/sqs-kafka-forwarder
          ports:
            - containerPort: 8080