apiVersion: v1
kind: Service
metadata:
  name: sqs-kafka-forwarder-svc
  namespace: factory
spec:
  selector:
    app: sqs-kafka-forwarder
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
