sqs:
  pressureQueue: PressureSQSQueue
  temperatureQueue: TemperatureSQSQueue
  noiseAndVibrationQueue: NoiseVibrationSQSQueue
  gasCompositionQueue: GasCompositionSQSQueue
  flowRateQueue: FlowRateSQSQueue
  isLocal: true
kafka:
  temperatureTopic: temperature
  pressureTopic: pressure
  noiseAndVibrationTopic: noiseAndVibration
  gasCompositionTopic: gasComposition
  flowRateTopic: flowRate
cloud:
  aws:
    region:
      static: eu-central-1
    credentials:
      access-key: AKIA3L7O27OZ5M6AXXX2
      secret-key: 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
    stack:
      auto: false
spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      bootstrap-servers: localhost:29092