sqs:
  pressureQueue: PressureSQSQueue
  temperatureQueue: TemperatureSQSQueue
  noiseAndVibrationQueue: NoiseVibrationSQSQueue
  gasCompositionQueue: GasCompositionSQSQueue
  flowRateQueue: FlowRateSQSQueue
  isLocal: true
kafka:
  temperatureTopic: temperature
  pressureTopic: pressure
  noiseAndVibrationTopic: noiseAndVibration
  gasCompositionTopic: gasComposition
  flowRateTopic: flowRate
cloud:
  aws:
    region:
      static: eu-central-1
    credentials:
      access-key: abc
      secret-key: abc
    stack:
      auto: false
spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      bootstrap-servers: localhost:29092
    schemaRegistryUrl: http://localhost:8081